order_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ordersys/', include('ordersys.urls',namespace = 'ordersys')),
    url(r'^$','ordersys.views.mainpage', name = 'mainpage'),
    url(r'^about/$','ordersys.views.about', name = 'about'),
]

ordersys/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /polls/
    #url(r'^$', views.index,  name='index'),
    url(r'^order/$',views.order, name = 'order'),
    url(r'^addorder/$',views.addorder, name = 'addorder'),
    url(r'^unfinishedorder/$',views.unfinorder, name = 'unfinorder'),
    url(r'^finishedoder/$',views.finorder, name = 'finorder'),
    url(r'^stat/$',views.stat, name = 'stat'),
    url(r'^statweek/$',views.statweek, name = 'statweek'),
    url(r'^endorder/$',views.endorder, name = 'endorder'),
    url(r'^delorder/$',views.delorder, name = 'delorder'),
    ]

order/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name =  models.CharField(max_length = 20)
    password = models.CharField(max_length = 10) 
    emp_type = models.IntegerField()

    def __unicode__(self):
        return self.name



class Order(models.Model):
    id = models.AutoField( primary_key = True )
    time = models.DateTimeField('date published')
    desk_id = models.IntegerField()
    total_price = models.FloatField()
    state = models.IntegerField()
    employee = models.ForeignKey(Employee)

    def __unicode__(self):
        return str(self.id)


class Tea(models.Model):
    name = models.CharField(max_length = 20)
    price = models.FloatField()

    def __unicode__(self):
        return self.name

class Order_Tea(models.Model):
    order = models.ForeignKey(Order)
    tea = models.ForeignKey(Tea)
    number = models.IntegerField()

    def __unicode__(self):
        return str(self.order_id)+','+str(self.tea_id)

order/views.py
from django.shortcuts import render

# Create your views here.

templates/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li class="active"><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div class="container">
        <div class="starter">
            <h1>关于本站</h1>
            <p class="lead">一个简单的点茶系统</p>
        </div>
    </div>

</body>
</html>

templates/addorder.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div class="container">
        <div class="starter">
            <h1>订单添加成功</h1>
            <a href="{%url 'ordersys:order'%}">返回</a>
        </div>
    </div>

       <div class="container">

</body>
</html>

templates/detail.html
{{ question }}
</br><p>{{question.id}}</p>
</br><p>{{question.question_text}}</p>
</br><p>{{question.pub_date}}</p>
</br>

<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method=post>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value={{choice.id}} />
    <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label></br>
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

templates/finorder.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li class="active"><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>
        <div class="container">
        <div class="starter">
            <h1>已完成订单</h1>
        </div>
        <a href="{%url 'ordersys:order'%}">返回</a>
    </div>

    {% for order in order_list %}
        <div class="container">
        <table class="table table-bordered" >
              <tbody >
                <tr>
                    <td colspan="1">订单号</td>
                    <td colspan="2">{{ order.id }}</td>
                    <td colspan="1">下单时间</td>
                    <td colspan="2">{{ order.time }}</td>
                </tr>

                <tr>
                    <td colspan="1">桌号</td>
                    <td colspan="1">{{ order.desk_id }}</td>
                    <td colspan="1">总价</td>
                    <td colspan="1">{{ order.total_price }}</td>
                    <td colspan="1">处理员工</td>
                    <td colspan="1">{{ order.employee.id }}</td>
                </tr>

                {% for item in order_tea_list %}
                {% if item.order.id == order.id %}
                <tr>
                    <td colspan="1">名称</td>
                    <td colspan="1">{{ item.tea.name }}</td>
                    <td colspan="1">单价</td>
                    <td colspan="1">{{ item.tea.price }}</td>
                    <td colspan="1">数量</td>
                    <td colspan="1">{{ item.number }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>                    
    {% endfor %}

</body>
</html>

templates/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/login.html
      <div class="container">

      <form class="form-signin" action="{% url 'ordersys:addorder'%}" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">ID</label>
        <input type="" id="inputID" name="inputID" class="form-control" placeholder="Employee ID" >
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->

templates/mainpage.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="#">查看统计</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="starter">
            <h1>欢迎来到点茶系统</h1>
            <p class="lead">赶紧开始点茶吧</p>
        </div>
    </div>

</body>
</html>

templates/order.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li class="active"><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div class="container">
        <div class="starter">
            <h1>茶品列表</h1>
        </div>

        <ul>
            {% for tea in tea_list %}
            <li>{{ tea.name }} -- {{ tea.price }} </li>
            {% endfor %}
        </ul>
    </div>

 
    <div class="container">
        <form class="form-inline" action="{% url 'ordersys:addorder'%}" method="post">
            <div class="form-group">
                <label for="exampleInputName2">茶品选择</label>
                <select name="select1" class="form-control">
                    {% for tea in tea_list %}
                    <option value="{{ tea.id }}">{{ tea.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail2">数量</label>
                <input type="text" name="number1" class="form-control" id="exampleInputEmail2" placeholder="1">
            </div>
            </br>
            <div class="form-group">
                <label for="exampleInputName2">茶品选择</label>
                <select name="select2" class="form-control">
                    {% for tea in tea_list %}
                    <option value="{{ tea.id }}">{{ tea.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail2">数量</label>
                <input type="text" name="number2" class="form-control" id="exampleInputEmail2" placeholder="1">
            </div>
            </br>
            <div class="form-group">
                <label for="exampleInputName2">茶品选择</label>
                <select name="select3" class="form-control">
                    {% for tea in tea_list %}
                    <option value="{{ tea.id }}">{{ tea.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail2">数量</label>
                <input type="text" name="number3" class="form-control" id="exampleInputEmail2" placeholder="1">
            </div>
            </br>
            <div class="form-group">
                <label for="exampleInputEmail2">桌号</label>
                <input type="text" name="deskid" class="form-control" id="exampleInputEmail2" placeholder="">
            </div>
            </br>
            <div class="form-group">
                <label for="exampleInputName2">工号</label>
                <select name="select4" class="form-control">
                    {% for emp in emp_list %}
                    <option value="{{ emp.id }}">{{ emp.id }}  {{ emp.name }}</option>
                    {% endfor %}
                </select>
            </div>
            </br>
            <button type="submit" class="btn btn-default">下单</button>
        </form>
    </div>

</body>
</html>

templates/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/stat.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li class="active"><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div id="main" style="height: 600px;border: 0px solid #ccc; padding: 10px;"></div>
    <script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
    <script type="text/javascript" language="javascript">
   require.config({
    paths: {
       echarts: 'http://echarts.baidu.com/build/dist'
        }
    });

    require([ 'echarts', 'echarts/chart/line','echarts/chart/bar' ], function(ec) {

      option = {
    title : {
        text: '今日销量统计',
        subtext: ''
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['销售量']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : [
            {% for row in sales %}
            '{{ row.1 }}',
            {% endfor %}
            ]
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'销售量',
            type:'bar',
            data:[
            {% for row in sales %}
            '{{ row.2 }}',
            {% endfor %}
            ],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            }
        },
    ]
};
            var relation = ec.init(document.getElementById('main'));
            relation.setOption(option);
    });

</script>
</body>
</html>

templates/statweek.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li class="active"><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div id="main" style="height: 600px;border: 0px solid #ccc; padding: 10px;"></div>
    <script src="http://echarts.baidu.com/build/dist/echarts.js"></script>
    <script type="text/javascript" language="javascript">
   require.config({
    paths: {
       echarts: 'http://echarts.baidu.com/build/dist'
        }
    });

    require([ 'echarts', 'echarts/chart/line','echarts/chart/bar' ], function(ec) {

        option = {
    title : {
        text: '最近三天销量变化',
        subtext: ''
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['销售量']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : [
            {% for row in sales %}
            '{{ row.1 }}',
            {% endfor %}
            ]
        }
    ],
    yAxis : [
        {
            type : 'value',
            axisLabel : {
                formatter: '{value}'
            }
        }
    ],
    series : [
        {
            name:'销售量',
            type:'line',
            data:[
            {% for row in sales %}
            '{{ row.2 }}',
            {% endfor %}
            ],
            markPoint : {
                data : [
                    
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name : '平均值'}
                ]
            }
        }
    ]
};
            var relation = ec.init(document.getElementById('main'));
            relation.setOption(option);
    });

</script>


</body>
</html>

templates/unfinoder.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="wdith=device-width,initial-scale=1">
    <title></title>
     <!-- Bootstrap core CSS -->
    <link href="http://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="http://v3.bootcss.com/dist/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v3.bootcss.com/examples/theme/theme.css" rel="stylesheet">
    <style>
        body {
            padding-top: 50px;
        }

        .starter{
            padding: 40px 15px;
            text-align: left;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="{% url 'mainpage'%}" class="navbar-brand">点茶系统</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'mainpage'%}">主页</a></li>
                    <li><a href="{% url 'ordersys:order' %}">开始点茶</a></li>
                    <li class="active"><a href="{% url 'ordersys:unfinorder' %}">未完成订单</a></li>
                    <li><a href="{% url 'ordersys:finorder' %}">已完成订单</a></li>
                    <li><a href="{% url 'ordersys:stat' %}">今日销量</a></li>
                    <li><a href="{% url 'ordersys:statweek' %}">本周销量</a></li>
                    <li><a href="{% url 'about' %}">关于本站</a> </li>
                </ul>
            </div>
        </div>
    </nav>

        <div class="container">
        <div class="starter">
            <h1>未完成订单</h1>
        </div>
        <a href="{%url 'ordersys:order'%}">返回</a>
    </div>

            <div class="container">
        <form class="form-inline" action="{% url 'ordersys:endorder'%}" method="post">
            <div class="form-group">
                <label for="exampleInputEmail2">订单号</label>
                <input type="text" name="order_id" class="form-control" id="exampleInputEmail2" placeholder="">
            </div>
            <button type="submit" class="btn btn-default">结帐</button>
        </br>
        </form>
    </div>

                <div class="container">
        <form class="form-inline" action="{% url 'ordersys:delorder'%}" method="post">
            <div class="form-group">
                <label for="exampleInputEmail2">订单号</label>
                <input type="text" name="order_id2" class="form-control" id="exampleInputEmail2" placeholder="">
            </div>
            <button type="submit" class="btn btn-default">撤销订单</button>
        </br>
        </form>
    </div>

    {% for order in order_list %}
        <div class="container">
        <table class="table table-bordered" >
              <tbody >
                <tr>
                    <td colspan="1">订单号</td>
                    <td colspan="2">{{ order.id }}</td>
                    <td colspan="1">下单时间</td>
                    <td colspan="2">{{ order.time }}</td>
                </tr>

                <tr>
                    <td colspan="1">桌号</td>
                    <td colspan="1">{{ order.desk_id }}</td>
                    <td colspan="1">总价</td>
                    <td colspan="1">{{ order.total_price }}</td>
                    <td colspan="1">处理员工</td>
                    <td colspan="1">{{ order.employee.id }}</td>
                </tr>

                {% for item in order_tea_list %}
                {% if item.order.id == order.id %}
                <tr>
                    <td colspan="1">名称</td>
                    <td colspan="1">{{ item.tea.name }}</td>
                    <td colspan="1">单价</td>
                    <td colspan="1">{{ item.tea.price }}</td>
                    <td colspan="1">数量</td>
                    <td colspan="1">{{ item.number }}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>                    
    {% endfor %}

</body>
</html>